// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGsXlk-NYwCRVZfvieG-DuvOrDKmDzeQ',
    appId: '1:729133876315:web:540ebcda24b3d5075b2b7e',
    messagingSenderId: '729133876315',
    projectId: 'geneio-8c5b2',
    authDomain: 'geneio-8c5b2.firebaseapp.com',
    storageBucket: 'geneio-8c5b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbBaJSCgdCRHB-Bgi84p6Pzs2gt2Ybvy4',
    appId: '1:729133876315:android:a8972e12da1bbcbc5b2b7e',
    messagingSenderId: '729133876315',
    projectId: 'geneio-8c5b2',
    storageBucket: 'geneio-8c5b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-T8fZ7nfG_AV36NyD9kbnrPOaucK1Lw',
    appId: '1:729133876315:ios:5109acda79ab6a105b2b7e',
    messagingSenderId: '729133876315',
    projectId: 'geneio-8c5b2',
    storageBucket: 'geneio-8c5b2.appspot.com',
    iosClientId:
        '729133876315-vi0uns4fdh410pdlfpf5upcb68bca660.apps.googleusercontent.com',
    iosBundleId: 'com.example.geneio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-T8fZ7nfG_AV36NyD9kbnrPOaucK1Lw',
    appId: '1:729133876315:ios:5109acda79ab6a105b2b7e',
    messagingSenderId: '729133876315',
    projectId: 'geneio-8c5b2',
    storageBucket: 'geneio-8c5b2.appspot.com',
    iosClientId:
        '729133876315-vi0uns4fdh410pdlfpf5upcb68bca660.apps.googleusercontent.com',
    iosBundleId: 'com.example.geneio',
  );
}
